# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-05 09:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity_99', models.DecimalField(decimal_places=2, max_digits=4)),
                ('director', models.CharField(max_length=100, null=True)),
                ('genre', models.TextField()),
                ('imdb_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Movielist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
